name: SAST pipeline Scan

on:
    push:
        branches:
            - main

jobs:
  analyze:
    name: Analyze code
    runs-on: ubuntu-latest

    strategy:
      matrix:
        language: [javascript]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Initialize CodeQL
        uses: github/codeql-action/init@v3
        with:
          languages: ${{matrix.language}}

      - name: Autobuild
        uses: github/codeql-action/autobuild@v3

      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v3
        with:
          output: results.sarif

      - name: Upload scan results
        uses: actions/upload-artifact@v4
        with:
          name: codeql-results
          path: results.sarif

